<?php

namespace AppBundle\Repository;

/**
 * BoissonsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoissonsRepository extends \Doctrine\ORM\EntityRepository
{
}
