imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr
    app.path.employees_images: /uploads/images/employees
    app.path.entrees_images: /uploads/images/entrees
    app.path.plats_images: /uploads/images/plats
    app.path.desserts_images: /uploads/images/desserts
    app.path.menus_images: /uploads/images/menus

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    #FOSCommentBundle
    http_method_override: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"
    registration:
            confirmation:
                enabled: true
    #profile:
    #        email_update_confirmation:
    #            enabled: true

# app/config/config.yml
easy_admin:
    entities:
        User:
            class: AppBundle\Entity\User
        Employees:
            class: AppBundle\Entity\Employees
            form:
                            fields:
                                - { property: 'nom', label: 'Nom'}
                                - { property: 'prenom', label: 'Prénom'}
                                - { property: 'poste', label: 'Poste occupé'}
                                - { property: 'enabled', label: 'Activer compte'}
                                - { property: 'imageFile', type: 'file', label: 'Ajouter' }
        Entrees:
            class: AppBundle\Entity\Entrees
            form:
                            fields:
                                - { property: 'name', label: 'Nom de l entrée'}
                                - { property: 'prix', label: 'Prix'}
                                - { property: 'imageFile', type: 'file', label: 'Ajouter image entree'}
        Plats:
            class: AppBundle\Entity\Plats
            form:
                            fields:
                                - { property: 'name', label: 'Nom du plat'}
                                - { property: 'prix', label: 'Prix'}
                                - { property: 'imageFile', type: 'file', label: 'Ajouter image du plat'}
        Desserts:
            class: AppBundle\Entity\Desserts
            form:
                            fields:
                                - { property: 'name', label: 'Nom du dessert'}
                                - { property: 'prix', label: 'Prix'}
                                - { property: 'imageFile', type: 'file', label: 'Ajouter image du dessert'}
        Boissons:
            class: AppBundle\Entity\Boissons
            form:
                            fields:
                                - { property: 'name', label: 'Nom de la boisson'}
                                - { property: 'prix', label: 'Prix'}
                                - { property: 'imageFile', type: 'file', label: 'Ajouter image de la boisson'}
        Menu:
                    class: AppBundle\Entity\Menu
                    form:
                            fields:
                                - { property: 'name', label: 'Nom du menu'}
                                - { property: 'entree', label: 'Entree'}
                                - { property: 'Plat', label: 'Plat'}
                                - { property: 'Boisson', label: 'Boisson'}
                                - { property: 'prix', label: 'Prix'}
                                - { property: 'imageFile', type: 'file', label: 'Ajouter image du menu'}
        Comment:
                    class: AppBundle\Entity\Comment
        Thread:
                    class: AppBundle\Entity\Thread
    design:
            form_theme: ['horizontal', 'VichUploaderBundle:Form:fields.html.twig']


vich_uploader:
    db_driver: orm
    mappings:
            employees_images:
                uri_prefix:         '%app.path.employees_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/employees'
                namer: vich_uploader.namer_uniqid
            entrees_images:
                uri_prefix:         '%app.path.entrees_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/entrees'
                namer: vich_uploader.namer_uniqid
            plats_images:
                uri_prefix:         '%app.path.plats_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/plats'
                namer: vich_uploader.namer_uniqid
            desserts_images:
                uri_prefix:         '%app.path.desserts_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/desserts'
                namer: vich_uploader.namer_uniqid
            menus_images:
                uri_prefix:         '%app.path.menus_images%'
                upload_destination: '%kernel.root_dir%/../web/uploads/images/menus'
                namer: vich_uploader.namer_uniqid

# app/config.yml
kms_froala_editor:
    language: "fr"

# app/config/config.yml
fos_comment:
    db_driver: orm
    class:
        model:
            comment: MyProject\MyBundle\Entity\Comment
            thread: MyProject\MyBundle\Entity\Thread

assetic:
    bundles: [ "FOSCommentBundle" ]

# app/config/config.yml
assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        cssrewrite: ~

